# MIYA HRV 新风系统配置示例
# 将此配置添加到您的 configuration.yaml 文件中

# 基本配置
miya_hrv:
  host: 192.168.1.5
  port: 38

# 日志配置（可选）
logger:
  default: info
  logs:
    custom_components.miya_hrv: debug

# 自动化示例
automation:
  # 空气质量差时开启净化功能
  - alias: "空气质量差时开启净化"
    description: "当空气质量指数超过100时自动开启净化功能"
    trigger:
      platform: numeric_state
      entity_id: sensor.air_quality
      above: 100
    condition:
      - condition: state
        entity_id: switch.miya_hrv_新风系统_净化功能
        state: "off"
    action:
      - service: switch.turn_on
        target:
          entity_id: switch.miya_hrv_新风系统_净化功能
      - service: notify.mobile_app
        data:
          title: "新风系统"
          message: "空气质量较差，已自动开启净化功能"

  # 晚上10点开启睡眠模式
  - alias: "晚上10点开启睡眠模式"
    description: "每天晚上10点自动开启睡眠模式"
    trigger:
      platform: time
      at: "22:00:00"
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
          - sat
          - sun
    action:
      - service: climate.set_preset_mode
        target:
          entity_id: climate.miya_hrv_新风系统
        data:
          preset_mode: sleep
      - service: climate.set_fan_mode
        target:
          entity_id: climate.miya_hrv_新风系统
        data:
          fan_mode: low

  # 早上7点关闭睡眠模式
  - alias: "早上7点关闭睡眠模式"
    description: "每天早上7点关闭睡眠模式，恢复正常模式"
    trigger:
      platform: time
      at: "07:00:00"
    action:
      - service: climate.set_preset_mode
        target:
          entity_id: climate.miya_hrv_新风系统
        data:
          preset_mode: null
      - service: climate.set_fan_mode
        target:
          entity_id: climate.miya_hrv_新风系统
        data:
          fan_mode: medium

  # 外出时开启假期模式
  - alias: "外出时开启假期模式"
    description: "当所有家庭成员都离家时开启假期模式"
    trigger:
      platform: state
      entity_id: group.family
      to: "not_home"
    condition:
      - condition: state
        entity_id: climate.miya_hrv_新风系统
        state: "on"
    action:
      - service: climate.set_preset_mode
        target:
          entity_id: climate.miya_hrv_新风系统
        data:
          preset_mode: vacation

  # 回家时关闭假期模式
  - alias: "回家时关闭假期模式"
    description: "当家庭成员回家时关闭假期模式"
    trigger:
      platform: state
      entity_id: group.family
      to: "home"
    condition:
      - condition: state
        entity_id: climate.miya_hrv_新风系统
        state: "on"
    action:
      - service: climate.set_preset_mode
        target:
          entity_id: climate.miya_hrv_新风系统
        data:
          preset_mode: null

# 脚本示例
script:
  # 会客模式脚本
  miya_hrv_guest_mode:
    alias: "会客模式"
    description: "开启会客模式，设置合适的风速和净化"
    sequence:
      - service: climate.set_preset_mode
        target:
          entity_id: climate.miya_hrv_新风系统
        data:
          preset_mode: guest
      - service: climate.set_fan_mode
        target:
          entity_id: climate.miya_hrv_新风系统
        data:
          fan_mode: medium
      - service: switch.turn_on
        target:
          entity_id: switch.miya_hrv_新风系统_净化功能
      - service: switch.turn_on
        target:
          entity_id: switch.miya_hrv_新风系统_外循环

  # 节能模式脚本
  miya_hrv_energy_save:
    alias: "节能模式"
    description: "开启节能模式，降低风速，关闭净化"
    sequence:
      - service: climate.set_fan_mode
        target:
          entity_id: climate.miya_hrv_新风系统
        data:
          fan_mode: low
      - service: switch.turn_off
        target:
          entity_id: switch.miya_hrv_新风系统_净化功能
      - service: switch.turn_on
        target:
          entity_id: switch.miya_hrv_新风系统_内循环

# 场景示例
scene:
  # 日常模式场景
  miya_hrv_daily:
    name: "日常模式"
    entities:
      climate.miya_hrv_新风系统:
        hvac_mode: "fan_only"
        fan_mode: "medium"
        preset_mode: null
      switch.miya_hrv_新风系统_净化功能:
        state: "on"
      switch.miya_hrv_新风系统_外循环:
        state: "on"
      switch.miya_hrv_新风系统_内循环:
        state: "off"

  # 睡眠模式场景
  miya_hrv_sleep:
    name: "睡眠模式"
    entities:
      climate.miya_hrv_新风系统:
        hvac_mode: "fan_only"
        fan_mode: "low"
        preset_mode: "sleep"
      switch.miya_hrv_新风系统_净化功能:
        state: "on"
      switch.miya_hrv_新风系统_外循环:
        state: "off"
      switch.miya_hrv_新风系统_内循环:
        state: "on"

  # 外出模式场景
  miya_hrv_away:
    name: "外出模式"
    entities:
      climate.miya_hrv_新风系统:
        hvac_mode: "fan_only"
        fan_mode: "low"
        preset_mode: "vacation"
      switch.miya_hrv_新风系统_净化功能:
        state: "off"
      switch.miya_hrv_新风系统_外循环:
        state: "off"
      switch.miya_hrv_新风系统_内循环:
        state: "off" 